# Tensor

In [5]:
import numpy as np
import torch

data = np.array([[1,2,3,4],[1,1,1,1]])
x = torch.tensor(data, device=None, dtype=torch.float32,requires_grad=False)
print("{}, {}".format(x,x.grad))
print(x+1)

tensor([[1., 2., 3., 4.],
        [1., 1., 1., 1.]]), None
tensor([[2., 3., 4., 5.],
        [2., 2., 2., 2.]])


In [22]:
x = torch.eye(4,dtype=None)
print(x)
x = torch.ones((4,4),dtype=None)
print(x)
x = torch.rand((2,2))
print(x)
x = torch.randn((2,2))
print(x)
x = torch.randint(1,3,(2,2))
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.7399, 0.8204],
        [0.5780, 0.2997]])
tensor([[ 1.0883, -0.9269],
        [ 1.5037,  0.4133]])
tensor([[2, 1],
        [1, 1]])


In [24]:
x = torch.tensor(1)
print(x.item())
x = torch.rand(2,3,5)
print(x)

1
tensor([[[0.4781, 0.2732, 0.6211, 0.7302, 0.9344],
         [0.6716, 0.1846, 0.7325, 0.8206, 0.4833],
         [0.8851, 0.5330, 0.3277, 0.0595, 0.0133]],

        [[0.6046, 0.0415, 0.4492, 0.2504, 0.3642],
         [0.4762, 0.8789, 0.8872, 0.4024, 0.4316],
         [0.5292, 0.0494, 0.4922, 0.0066, 0.7376]]])


In [ ]:
## Tensor 的连接

In [32]:
x = torch.ones(3,3)
y = torch.ones(3,3)*2
print(x)
print(y)
print(torch.cat((x,y),0))
print(torch.cat((x,y),1))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [35]:
x = torch.ones(2,2,2)
y = torch.ones(2,2,2)*2
print(x)
print(y)
print(torch.cat((x,y),2))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])
tensor([[[1., 1., 2., 2.],
         [1., 1., 2., 2.]],

        [[1., 1., 2., 2.],
         [1., 1., 2., 2.]]])
