# 线性代数
标量是只有一个元素的量，向量是由n个标量组成的数组，向量是标量的推广，矩阵是标量的推广，张量是矩阵的推广

## 标量

In [8]:
import numpy as np
x = np.array(2)
y = np.array(3)
print(x)
print(y)
print(x+y, x*y, x/y, x**y)

2
3
5 6 0.6666666666666666 8


## 向量
可以理解为一维数组，是标量的推广, size: 元素个数总和，shape: 向量的维度

In [15]:
x = np.arange(10)
print("Vector: {}, {}, {}, {}, size: {}, shape: {}".format(x, x[3], x[1:4],x[-1],x.size,x.shape))

Vector: [0 1 2 3 4 5 6 7 8 9], 3, [1 2 3], 9, size: 10, shape: (10,)


## 矩阵
可以理解为二位数组，有两个维度

In [17]:
x = np.arange(9).reshape(3, 3)
print(x)
print(x.T)
print(x==x.T)
print("{}, {}".format(x.size, x.shape))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[ True False False]
 [False  True False]
 [False False  True]]
9, (3, 3)


## 张量
可以理解为有n个维度的矩阵

In [19]:
x = np.arange(24).reshape(2,3,4)
print(x)
print("size: {}, shape: {}".format(x.size, x.shape))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
size: 24, shape: (2, 3, 4)


In [ ]:
## 降维

In [25]:
x = np.arange(12).reshape(3,4)
print(x)
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))
print(x.sum(axis=0, keepdims=True))
print(x.sum(axis=1, keepdims=True))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
66.0
[12. 15. 18. 21.]
[ 6. 22. 38.]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]
[[12. 15. 18. 21.]]
[[ 6.]
 [22.]
 [38.]]
