# 线性代数
标量是只有一个元素的量，向量是有n个标量组成的列表，向量是标量的推广，矩阵是标量的推广，张量是矩阵的推广
## 标量

In [8]:
from mxnet import np, npx
npx.set_np()

x = np.array(2)
y = np.array(3)
print(x, y)
print(x+y, x*y, x/y, x**y)

2.0 3.0
5.0 6.0 0.6666667 8.0


## 向量

In [12]:
x = np.arange(10)
print(x)
print(x[3])
print(x[1:4])
print(x[-1])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
3.0
[1. 2. 3.]
9.0


## 矩阵

In [18]:
x = np.arange(9).reshape(3, 3)
print(x)
print(x.T)
print(x==x.T)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0. 3. 6.]
 [1. 4. 7.]
 [2. 5. 8.]]
[[ True False False]
 [False  True False]
 [False False  True]]


## 张量

In [19]:
x = np.arange(24).reshape(2,3,4)
print(x)


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
